### ISSUE TITLE
Yelp API Security Key Issue

### ISSUE THREAD

**Issue by zoejab** [zoejab/Pizza_Party#1]
@jasonseminara @zhenpanda @amcooper @WilliamfShaw

Context

When submitting an issue provide some context as to what the problem is. This includes but is not limited to:

What User Story you are currently working on
-n/a i'm trying to make sure the API key is secure - there's a few extra steps needed for the Yelp API

What you are trying to do
- get my API started and running

Detailed description of the bug or error

FROM TERMINAL
 b = HTTParty.get('https://api.yelp.com/v2/search/?term=pizza&location=New York, New York&sort=2&limit=20')

=> {"error"=>
  {"text"=>"One or more parameters are missing in request",
   "id"=>"MISSING_PARAMETER",
   "field"=>"oauth_consumer_key"}}

Relevant code/files/errors, screenshots
https://github.com/Yelp/yelp-ruby

https://github.com/yelp/yelp-rails-example
this has the gem

What have you tried?
researched and could figure it out but I want to make sure its actually secure.

What would you like help with specifically?
Yelp API!

**Comment by WilliamfShaw** [comment]
I think we solved this yeah?
