### ISSUE TITLE
Updating comments Routing Errors

### ISSUE THREAD

**Issue by zoejab** [zoejab/Pizza_Party#2]
@jasonseminara @zhenpanda @amcooper @WilliamfShaw

Context

When submitting an issue provide some context as to what the problem is. This includes but is not limited to:

What User Story you are currently working on
allowing a user to edit and update a comment. I have delete working but the paths it says it needs aren't working in relation to my rake routes options

What you are trying to do
posting/updating the edit. it's really a matter of routing errors

Detailed description of the bug or error

No route matches [POST] "/pizza_places/5/comments/15/edit"

Relevant code/files/errors, screenshots

What have you tried?
a lot of research led me to try a resources: pizza_places do resources: comments only (create) which solved some issues and caused others. Then I tried with the multiple routes according to my rake routes but I'm really not sure what the error is

What would you like help with specifically?
another set of eyes and maybe a little bit of hand holding to get this working.

**Comment by jasonseminara** [comment]
fixed. done.
